---
- name: Upgrade apt packages on cluster
  hosts: cluster
  gather_facts: false
  become: true

  tasks:
    - name: Update and upgrade apt packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: full
  
    - name: Check if reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: false
      register: reboot_required_file
  
    - name: Reboot if required
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists == true
  
    - name: Removed dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: true
